# Generated by Django 6.0.3 on 2026-04-25 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guide',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='invitation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages_spoken',
            field=models.CharField(default='Bengali, English', max_length=500),
        ),
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
